import type { Metadata } from "next";
import { Gilda_Display, PT_Serif } from "next/font/google";
import "./globals.css";
import { ConsultationProvider } from "@/component/consultation-form";
import { cloudinaryImages } from "@/lib/cloudinary-images";

// Headings only
const gildaDisplay = Gilda_Display({
  variable: "--font-gilda",
  weight: "400",
  subsets: ["latin"],
});

// Everything else
const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: cloudinaryImages.icon,
    shortcut: cloudinaryImages.icon,
    apple: cloudinaryImages.icon,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${gildaDisplay.variable} ${ptSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ConsultationProvider>{children}</ConsultationProvider>
      </body>
    </html>
  );
}
